"""empty message

Revision ID: 18b69544e79b
Revises: 5ece159e45b9
Create Date: 2021-03-13 01:12:25.867681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b69544e79b'
down_revision = '5ece159e45b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'disliked', ['tag_id'])
    op.create_unique_constraint(None, 'highlights', ['game_id'])
    op.create_unique_constraint(None, 'liked', ['tag_id'])
    op.create_unique_constraint(None, 'now_playing', ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'now_playing', type_='unique')
    op.drop_constraint(None, 'liked', type_='unique')
    op.drop_constraint(None, 'highlights', type_='unique')
    op.drop_constraint(None, 'disliked', type_='unique')
    # ### end Alembic commands ###
