"""empty message

Revision ID: 21945c021928
Revises: 10d67fce0b7e
Create Date: 2021-02-17 05:24:46.623339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21945c021928'
down_revision = '10d67fce0b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('list_name', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'favorites', ['list_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_column('favorites', 'list_name')
    # ### end Alembic commands ###
