"""empty message

Revision ID: 2b409dd6c980
Revises: 18b69544e79b
Create Date: 2021-03-16 14:35:30.294422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b409dd6c980'
down_revision = '18b69544e79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag_id', table_name='disliked')
    op.drop_index('game_id', table_name='favorite_list')
    op.drop_index('game_id', table_name='highlights')
    op.drop_index('tag_id', table_name='liked')
    op.drop_index('game_id', table_name='now_playing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('game_id', 'now_playing', ['game_id'], unique=True)
    op.create_index('tag_id', 'liked', ['tag_id'], unique=True)
    op.create_index('game_id', 'highlights', ['game_id'], unique=True)
    op.create_index('game_id', 'favorite_list', ['game_id'], unique=True)
    op.create_index('tag_id', 'disliked', ['tag_id'], unique=True)
    # ### end Alembic commands ###
