"""empty message

Revision ID: 2d4adbac1d84
Revises: c02b1d28f17d
Create Date: 2021-03-17 01:19:52.383783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d4adbac1d84'
down_revision = 'c02b1d28f17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('completed_id', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('completed_name', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('finished_id', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('finished_name', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('started_id', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('started_name', sa.String(length=120), nullable=True))
    op.drop_column('highlights', 'started')
    op.drop_column('highlights', 'finished')
    op.drop_column('highlights', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('completed', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('highlights', sa.Column('finished', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('highlights', sa.Column('started', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('highlights', 'started_name')
    op.drop_column('highlights', 'started_id')
    op.drop_column('highlights', 'finished_name')
    op.drop_column('highlights', 'finished_id')
    op.drop_column('highlights', 'completed_name')
    op.drop_column('highlights', 'completed_id')
    # ### end Alembic commands ###
