"""empty message

Revision ID: 33abe96cc9c6
Revises: 762402052503
Create Date: 2021-02-17 04:34:48.644152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33abe96cc9c6'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('profile_avatar', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'profile_avatar')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'joined')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
