"""empty message

Revision ID: 4097c83be990
Revises: 33abe96cc9c6
Create Date: 2021-02-17 04:44:53.631072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4097c83be990'
down_revision = '33abe96cc9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('now_playing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=250), nullable=False),
    sa.Column('game_name', sa.String(length=250), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('game_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('now_playing')
    # ### end Alembic commands ###
