"""empty message

Revision ID: 4f70f1da8e4e
Revises: 
Create Date: 2021-02-23 14:51:30.894410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f70f1da8e4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('profile_avatar', sa.String(length=250), nullable=False),
    sa.Column('joined', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('about_me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('about_box', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=250), nullable=False),
    sa.Column('game_name', sa.String(length=250), nullable=False),
    sa.Column('game_platform', sa.String(length=250), nullable=False),
    sa.Column('game_notes', sa.String(length=500), nullable=False),
    sa.Column('progress_status', sa.Enum('NEW', 'PROGRESSING', 'FINISHED', 'COMPLETED', name='progressionstatus'), nullable=True),
    sa.Column('now_playing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('game_name'),
    sa.UniqueConstraint('game_platform')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=250), nullable=False),
    sa.Column('game_name', sa.String(length=250), nullable=False),
    sa.Column('list_name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('game_name'),
    sa.UniqueConstraint('list_name')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_backlog_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=250), nullable=False),
    sa.Column('game_genre', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_backlog_id'], ['backlog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_genre'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    op.drop_table('favorites')
    op.drop_table('backlog')
    op.drop_table('about_me')
    op.drop_table('user')
    # ### end Alembic commands ###
