"""empty message

Revision ID: 5ece159e45b9
Revises: ddd313d53745
Create Date: 2021-03-08 23:43:48.086744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ece159e45b9'
down_revision = 'ddd313d53745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('game_name', table_name='favorite_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('game_name', 'favorite_list', ['game_name'], unique=True)
    # ### end Alembic commands ###
