"""empty message

Revision ID: 9e4248f15bde
Revises: 21945c021928
Create Date: 2021-02-17 06:05:36.314485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4248f15bde'
down_revision = '21945c021928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=250), nullable=False),
    sa.Column('game_name', sa.String(length=250), nullable=False),
    sa.Column('game_platform', sa.String(length=250), nullable=False),
    sa.Column('uncleared', sa.String(length=10), nullable=False),
    sa.Column('in_progress', sa.String(length=10), nullable=False),
    sa.Column('finished', sa.String(length=10), nullable=False),
    sa.Column('completed', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('game_name'),
    sa.UniqueConstraint('game_platform')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backlog')
    # ### end Alembic commands ###
