"""empty message

Revision ID: c02b1d28f17d
Revises: ed3de73a2ed8
Create Date: 2021-03-17 00:18:01.343047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c02b1d28f17d'
down_revision = 'ed3de73a2ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('completed', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('finished', sa.String(length=120), nullable=True))
    op.add_column('highlights', sa.Column('started', sa.String(length=120), nullable=True))
    op.drop_column('highlights', 'game_id')
    op.drop_column('highlights', 'game_name')
    op.add_column('platform', sa.Column('platform_id', sa.String(length=120), nullable=True))
    op.add_column('platform', sa.Column('platform_name', sa.String(length=120), nullable=True))
    op.drop_column('platform', 'started')
    op.drop_column('platform', 'finished')
    op.drop_column('platform', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('completed', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('platform', sa.Column('finished', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('platform', sa.Column('started', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('platform', 'platform_name')
    op.drop_column('platform', 'platform_id')
    op.add_column('highlights', sa.Column('game_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('highlights', sa.Column('game_id', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('highlights', 'started')
    op.drop_column('highlights', 'finished')
    op.drop_column('highlights', 'completed')
    # ### end Alembic commands ###
