"""empty message

Revision ID: cc111ee989c6
Revises: 9404237c1dfc
Create Date: 2021-03-18 00:33:33.184157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc111ee989c6'
down_revision = '9404237c1dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_dislike', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('tag_dislike', 'tag_name')
    op.drop_column('tag_dislike', 'tag_id')
    op.drop_column('tag_like', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_like', sa.Column('tag_id', mysql.VARCHAR(length=25), nullable=True))
    op.add_column('tag_dislike', sa.Column('tag_id', mysql.VARCHAR(length=25), nullable=True))
    op.add_column('tag_dislike', sa.Column('tag_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('tag_dislike', 'name')
    # ### end Alembic commands ###
