"""empty message

Revision ID: d33f1fd99e10
Revises: bbdf74e03a9f
Create Date: 2021-02-20 01:45:15.213246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd33f1fd99e10'
down_revision = 'bbdf74e03a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog', sa.Column('Progress_status', sa.Enum('NEW', 'PROGRESSING', 'FINISHED', 'COMPLETED', name='progressionstatus'), nullable=True))
    op.add_column('backlog', sa.Column('game_notes', sa.String(length=500), nullable=False))
    op.drop_column('backlog', 'completed')
    op.drop_column('backlog', 'in_progress')
    op.drop_column('backlog', 'uncleared')
    op.drop_column('backlog', 'finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog', sa.Column('finished', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('backlog', sa.Column('uncleared', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('backlog', sa.Column('in_progress', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('backlog', sa.Column('completed', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('backlog', 'game_notes')
    op.drop_column('backlog', 'Progress_status')
    # ### end Alembic commands ###
