"""empty message

Revision ID: dc272a792f2b
Revises: 4f70f1da8e4e
Create Date: 2021-02-23 16:03:32.354668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc272a792f2b'
down_revision = '4f70f1da8e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('game_name', table_name='backlog')
    op.drop_index('game_platform', table_name='backlog')
    op.alter_column('user', 'profile_avatar',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_avatar',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.create_index('game_platform', 'backlog', ['game_platform'], unique=True)
    op.create_index('game_name', 'backlog', ['game_name'], unique=True)
    # ### end Alembic commands ###
