"""empty message

Revision ID: ddd313d53745
Revises: 7952c4d076b6
Create Date: 2021-03-08 23:42:03.864895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd313d53745'
down_revision = '7952c4d076b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'favorite_list', ['game_id'])
    op.create_unique_constraint(None, 'favorite_list', ['game_name'])
    op.alter_column('now_playing', 'game_id',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('now_playing', 'game_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('now_playing', 'game_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('now_playing', 'game_id',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint(None, 'favorite_list', type_='unique')
    op.drop_constraint(None, 'favorite_list', type_='unique')
    # ### end Alembic commands ###
