"""empty message

Revision ID: e014e74cf313
Revises: aa4d7359d4e2
Create Date: 2021-02-25 19:31:36.864523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e014e74cf313'
down_revision = 'aa4d7359d4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_tags', table_name='tags')
    op.drop_table('tags')
    op.add_column('backlog', sa.Column('game_tags', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backlog', 'game_tags')
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_tags', mysql.VARCHAR(length=25), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tags_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_tags', 'tags', ['user_tags'], unique=True)
    # ### end Alembic commands ###
