"""empty message

Revision ID: e6739be72fa2
Revises: cc111ee989c6
Create Date: 2021-03-18 00:35:36.895519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6739be72fa2'
down_revision = 'cc111ee989c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_like', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('tag_like', 'tag_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_like', sa.Column('tag_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('tag_like', 'name')
    # ### end Alembic commands ###
