"""empty message

Revision ID: ed3de73a2ed8
Revises: 7e208c83c6df
Create Date: 2021-03-17 00:02:51.764409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed3de73a2ed8'
down_revision = '7e208c83c6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('completed', sa.String(length=120), nullable=True))
    op.add_column('platform', sa.Column('finished', sa.String(length=120), nullable=True))
    op.add_column('platform', sa.Column('started', sa.String(length=120), nullable=True))
    op.drop_column('platform', 'platform_id')
    op.drop_column('platform', 'platform_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('platform_name', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('platform', sa.Column('platform_id', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('platform', 'started')
    op.drop_column('platform', 'finished')
    op.drop_column('platform', 'completed')
    # ### end Alembic commands ###
