"""empty message

Revision ID: fdee456a656c
Revises: d33f1fd99e10
Create Date: 2021-02-20 01:54:24.457897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdee456a656c'
down_revision = 'd33f1fd99e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog', sa.Column('progress_status', sa.Enum('NEW', 'PROGRESSING', 'FINISHED', 'COMPLETED', name='progressionstatus'), nullable=True))
    op.drop_column('backlog', 'Progress_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog', sa.Column('Progress_status', mysql.ENUM('NEW', 'PROGRESSING', 'FINISHED', 'COMPLETED'), nullable=True))
    op.drop_column('backlog', 'progress_status')
    # ### end Alembic commands ###
